name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install .NET tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Generate AssemblyInfo
        run: dotnet dotnet-gitversion /updateprojectfiles /output buildserver
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Add GitHub Packages source
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget add source --username johnnycederholm --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/johnnycederholm/index.json"
      - name: Publish NuGet package
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push src/WorkerService.Testing/bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "github"
